FROM balenalib/%%BALENA_ARCH%%-node:10.19.0-stretch-build as build
COPY server/package.json package.json
COPY server/package-lock.json package-lock.json
RUN npm install --production

FROM balenalib/%%BALENA_ARCH%%-node:10.19.0-stretch-run
COPY --from=build ./node_modules ./server/node_modules
COPY ./server ./server
WORKDIR server

CMD ["npm", "start"]
